# Generated by Django 4.2.1 on 2023-08-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CODD', models.CharField(max_length=20, unique=True)),
                ('Names', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NSchool', models.CharField(max_length=50)),
                ('NCarrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COD', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('Materia', models.CharField(max_length=50, verbose_name='Subject')),
                ('semestre', models.CharField(max_length=50, verbose_name='Semester')),
                ('Cupos', models.IntegerField(verbose_name='Space')),
                ('CODDO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.docente')),
                ('M_Escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.escuela')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='D_Escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.escuela'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODA', models.CharField(max_length=50)),
                ('ocupdia', models.CharField(max_length=50, null=True)),
                ('start', models.CharField(max_length=50, null=True)),
                ('end', models.CharField(max_length=50, null=True)),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.materia', verbose_name='Subject')),
            ],
        ),
    ]
