# Generated by Django 4.2.1 on 2023-08-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='cupoA',
            field=models.IntegerField(null=True, verbose_name='SubjectA'),
        ),
    ]
